apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-config
  namespace: maersk-booking
data:
  availability.base-url: http://wiremock.maersk-booking.svc.cluster.local:8080
  availability.path: /api/bookings/checkAvailable
---
apiVersion: v1
kind: Secret
metadata:
  name: booking-secret
  namespace: maersk-booking
type: Opaque
stringData:
  API_KEY_VALUE: dev-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-backend
  namespace: maersk-booking
spec:
  replicas: 1
  selector:
    matchLabels: { app: booking-backend }
  template:
    metadata:
      labels: { app: booking-backend }
    spec:
      containers:
        - name: backend
          image: ghcr.io/your/repo/booking-backend:latest
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo.maersk-booking.svc.cluster.local:27017/maersk_booking
            - name: availability.base-url
              valueFrom:
                configMapKeyRef:
                  name: booking-config
                  key: availability.base-url
            - name: availability.path
              valueFrom:
                configMapKeyRef:
                  name: booking-config
                  key: availability.path
            - name: security.api-key.enabled
              value: "true"
            - name: security.api-key.header
              value: "X-API-KEY"
            - name: security.api-key.value
              valueFrom:
                secretKeyRef:
                  name: booking-secret
                  key: API_KEY_VALUE
          ports: [{ containerPort: 8080 }]
---
apiVersion: v1
kind: Service
metadata:
  name: booking-backend
  namespace: maersk-booking
spec:
  selector: { app: booking-backend }
  ports:
    - port: 8080
      targetPort: 8080
