apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiremock
  namespace: maersk-booking
spec:
  replicas: 1
  selector:
    matchLabels: { app: wiremock }
  template:
    metadata:
      labels: { app: wiremock }
    spec:
      containers:
        - name: wiremock
          image: wiremock/wiremock:3.9.1
          args: ["--port","8080"]
          ports: [{ containerPort: 8080 }]
---
apiVersion: v1
kind: Service
metadata:
  name: wiremock
  namespace: maersk-booking
spec:
  selector: { app: wiremock }
  ports:
    - port: 8080
      targetPort: 8080
